exp_name: nyt
data_in_dir: ../ori_data
ori_data_format: raw_nyt # casrel, etl_span, raw_nyt, tplinker

# if build data for BERT, use these 3 lines and comment the following 2 lines.
encoder: BERT
bert_path: ../../pretrained_models/bert-base-cased #  chinese-roberta-wwm-ext
data_out_dir: ../data4bert

# if build data for BiLSTM, use these 2 lines and comment above 3 lines.
# encoder: BiLSTM
# data_out_dir: ../data4bilstm

# if only reproduce the results, no need to change the args below.
# separate_char_by_white: e.g. "$%sdkn839," -> "$% sdkn839 ," , will make original char spans invalid
# add_char_span: set add_char_span to false if it already exists
# ignore_subword: when adding character level spans, match words with whitespace around: " word ", to avoid subword match
# check_tok_span: check whether there is any error with token spans, if there is, print the unmatch info
add_char_span: true
ignore_subword: true
separate_char_by_white: false
check_tok_span: true
